# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14.5-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - "./schema-and-data.sql:/docker-entrypoint-initdb.d/1.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
